version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  url-shortener-service:
    build: ./url-shortener-service
    container_name: url-shortener-service
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SESSION_SECRET: ${SESSION_SECRET}
      GUEST_ID: ${GUEST_ID}

  url-redirection-service:
    build: ./url-redirection-service
    container_name: url-redirection-service
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - url-shortener-service
      - url-redirection-service
